# Generated by Django 6.1.2 on 2026-10-09 16:33

from django.db import migrations

SEED_SKILLS = ["HVAC", "Electrical", "Appliance Repair"]


def seed_skills(apps, schema_editor):
    Skill = apps.get_model("api", "Skill")
    for name in SEED_SKILLS:
        Skill.objects.get_or_create(name=name)


def unseed_skills(apps, schema_editor):
    Skill = apps.get_model("api", "Skill")
    Skill.objects.filter(name__in=SEED_SKILLS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_skills, unseed_skills),
    ]
